### ISSUE TITLE
作者 我有一个提议 这样可能可以让插件变得更好

### ISSUE THREAD

**Issue by konglai55** [moewhite19/BNes#1]
请问是否能在下个版本加入自定义卡带lore和name呢 
默认的名字和lore未免太单调了
还有是否能加入卡带物品custom-model-data
这样可以用材质包实现卡带的更多样子
:)

**Comment by Q2297045667** [comment]
这个提议很好

**Comment by moewhite19** [comment]
这个你们决定，我这边是不参与custom-moedel-data的使用和检查的
只要你自己想办法把卡带加上这个属性不影响正常用的x
